### ISSUE TITLE
MPI Cluster Parallelization

### ISSUE THREAD

**Issue by fabiansiuda** [luca-scr/GA#19]
Hi,

I'm trying to run GA in parallel on a MPI Cluster but GA does not seem to support parallelizations via MPI cluster.

Apparently, the check (https://github.com/luca-scr/GA/blob/master/R/parallel.R#L12) in line 12 returns FALSE for MPI cluster, which will then be used in lines 157+ (e.g. https://github.com/luca-scr/GA/blob/master/R/ga.R#L157 and https://github.com/luca-scr/GA/blob/master/R/ga.R#L172) for the parallelization procedure.
MPI Cluster have the Classes ["nbmpicluster", "mpicluster", "dompicluster"], for which line 12 will produce the following structure for the parallel object:
>str(parallel)
atomic [1:1] FALSE
 - attr(*, "type")= chr "multicore"
 - attr(*, "cores")= int 28

I was wondering if there is a way to allow for MPI Cluster parallelization.

Thanks.

**Comment by luca-scr** [comment]
I don't have access or experience with MPI clusters, so I can be of any help.
You may want to look at http://luca-scr.github.io/GA/articles/GA.html#parallel-computing to see the available options. 
If you want to add MPI parallelisation you are welcome.
