### ISSUE TITLE
Can not find function "parNames"

### ISSUE THREAD

**Issue by ChiHangChen** [luca-scr/GA#20]
I want to add progress bar in GA::ga function, so I paste the ga source code into my R script and modify it,
but it shows error " can not find function parNames", and I cant find the source code of function "parNames".

**Comment by luca-scr** [comment]
parNames is not a function, it's a method associated to the S4 object 'ga'. 
You  may want to take a look at the source code for its definition.

**Comment by ChiHangChen** [comment]
Thanks a million , I fix the problem.
