### ISSUE TITLE
Cannot Quiet GA run

### ISSUE THREAD

**Issue by svarsen** [luca-scr/GA#21]
Hello,
This is a rather minor problem but I am unable to quiet the output from the GA function. It does not respond to the invisible() command or implementation of the quiet=TRUE parameter. Any idea why this is occurring?
Thanks,
Sam

**Comment by luca-scr** [comment]
If I correctly understood your problem, you are looking at the wrong direction. invisible() function is used for different purposes, and quiet is not an argument of ga().
I guess you should look at the argument "monitor" in help(ga).
