### ISSUE TITLE
print current solution in monitor function

### ISSUE THREAD

**Issue by maxrodkin** [luca-scr/GA#26]
hello!
i`d liketo debug my ga. cancerning that, i tryed to print current solution in monitor function
```
monitor <- function(obj) 
{ 
  #gaMonitor(obj)
  browser()
  print(c("iteration =", obj@iter , "solution =" , obj@solution))
}
```
but obj@solution is empty
```
Called from: monitor(object)
Browse[1]> obj@solution
<0 x 0 matrix>
```
Call:
ga(type = "real-valued", fitness = fitness, lower = rep(0,     nrow(UsingInstr)), upper = rep(1, nrow(UsingInstr)), pcrossover = 0.05,     maxiter = 50000, run = 100, names = files, suggestions = rep(1/nrow(UsingInstr),         nrow(UsingInstr)), parallel = TRUE, monitor = monitor,     seed = 1)
How to print solution in iteration?

**Comment by luca-scr** [comment]
Please update the package with the current version available in GitHub.
Then
```
library(GA)

f <- function(x)  (x^2+x)*cos(x) # -10 < x < 10

monitor <- function(obj) 
{ 
  cat(paste("iteration =", obj@iter , "solution =" , obj@bestSol[[obj@iter]]), "\n")
}

GA <- ga(type = "real-valued", fitness = f, lower = -10, upper = 10, 
         keepBest = TRUE, monitor = monitor)
```

**Comment by luca-scr** [comment]
Please try the following and check that your output matches:

```
> packageDescription("GA")$Version
[1] "3.2.1"
> packageDescription("GA")$Date
[1] "2019-05-29"
```

**Comment by maxrodkin** [comment]
@luca-scr , you was right!
now i got desired monitoring

**Comment by gokhale616** [comment]
@luca-scr - Extending the following thread. Is it possible to store the population at every evolutionary iteration rather than have it printed? I am thinking of a user defined slot in ga to store a list of population matrices from first to last iteration?
