### ISSUE TITLE
How to debug GA function from GA package?

### ISSUE THREAD

**Issue by maxrodkin** [luca-scr/GA#27]
I ran GA function from R GA package for securties portfolio optimization. Its correct for shares and bonds separatelly. Id like to combine s.&b. in one porfolio. Thus, i combined the both datasets in one. But got error about "as.vector(nBits)" , but i have no such expression in my code. How to understand, which my GA parameter is wrong?
Error in as.vector(nBits) : argument "nBits" is missing, with no default

I posted Q. [here](https://stackoverflow.com/questions/56472941/how-to-debug-ga-function-from-ga-package) too.
My issue not bug report, but help request

**Comment by luca-scr** [comment]
See the reply you got on StackOverflow.

**Comment by maxrodkin** [comment]
@luca-scr thank you
