### ISSUE TITLE
Log messages in parallel mode

### ISSUE THREAD

**Issue by tamas-ferenci** [luca-scr/GA#32]
When using `parallel=TRUE`, absolutely no information is returned on the console from the fitness function itself. Is it somehow possible to save the messages of the function? I was thinking of something like the `outfile` option of the `makeCluster`, but unfortunately I can not set it from the outside in `GA` (if I understand everything correctly).

**Comment by luca-scr** [comment]
Have you tried to create a cluster "from scratch" with  makeCluster() with `outfile` set and provide the cluster to the parallel argument of ga()?
Please see an example of setting a cluster at http://luca-scr.github.io/GA/articles/GA.html#parallel-computing
