### ISSUE TITLE
Does type  "binary" feed the fitness function with gray encoded individuals?

### ISSUE THREAD

**Issue by Paul-AntoineLeboeuf** [luca-scr/GA#34]
Hi,  nice package by the way. 

Why in your **Binary search solution** of your **A quick tour of GA** document, you have to used the function _gray2binary_ on the "x" argument before  moving on (as I understand it, this argument  represents the individuals). It looks like the GA function gives gray encoding individuals to the fitness function when the GA "binary" type is used instead of just binary encoded individuals.
Thanks

**Comment by luca-scr** [comment]
The use of Gray encoding in binary search is explained in the JSS paper.
