### ISSUE TITLE
Multi objective optimization using the GA Library 

### ISSUE THREAD

**Issue by swaheera** [luca-scr/GA#55]
Hello, 

Currently, is the GA library capable of performing multi objective optimization? For example, something like this? 

https://stackoverflow.com/questions/56359838/argument-passing-in-r-to-functions-of-several-real-variables

Thanks

**Comment by luca-scr** [comment]
It depends on what you mean by multi objective optimization. In general, GA package can't perform multi objective optimization. However, if you can re-express your multi objective optimization problem into a single fitness function optimization over multiple parameters., then you can use GA package.
