### ISSUE TITLE
Perhaps there is an error in the README file

### ISSUE THREAD

**Issue by matteodefelice** [luca-scr/GA#6]
Installed the package with devtools...done. 
loaded the package with `library(GA)`
as suggested in the README I have tried to show the vignette...
```
> vignette("GA")
Warning message:
vignette ‘GA’ not found 
```

**Comment by luca-scr** [comment]
It seems that by default the vignette is not built.

You could try

devtools::install_github("luca/GA", build_vignettes = FALSE)

or install the CRAN version which surely has the vignette already build.

**Comment by matteodefelice** [comment]
Same again:
```
> devtools::install_github("luca-scr/GA", build_vignettes = T)
[...]
> vignette('GA')
Warning message:
vignette ‘GA’ not found 
```

**Comment by luca-scr** [comment]
Remove the package first

remove.packages("GA")

and then install from GitHub. It did work for me, so it should also for you.

LS

**Comment by matteodefelice** [comment]
Great! Thank you, now it works!
