### ISSUE TITLE
Discrete input parameters

### ISSUE THREAD

**Issue by oriongod1** [luca-scr/GA#9]
What changes are to be made so that the input parameters are considered to be discrete/integer values.
1. Making high penalties in the fitness function is not the right option as it becomes a part of the iterative process. 
2. skipping the non-integer values is again a part of iterative process. 

Something needs to be changed in: 
ga(type = c("binary", "real-valued", "permutation"),
min, max, nBits, fitness, ..., )
to make the algo take in only integer/ discrete parameters. I have four discrete params.
 
I cant figure it out :( 
Thanks..

**Comment by luca-scr** [comment]
If you have discrete/integer values for your decision variables, you have two options:

1. use `type = "binary"` search by encoding your decision variables as binary values
2. use `type = "real-valued"`  by encoding your decision variables as floating-point values in a specified range and apply some repairing to convert the values to integers. 

For an example of both approaches see Section 4.6 of the following paper

- Scrucca L. (2013) GA: A Package for Genetic Algorithms in R. **Journal of Statistical Software**, Vol. 53, Issue 4, pp. 1–37. http://www.jstatsoft.org/v53/i04

Best,

Luca
